version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: ch_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin_password
      MYSQL_DATABASE: collectorhub
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

volumes:
  db_data: