# URL real de Railway
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Clave secreta para firmar los token JWT
jwt.secret=${JWT_SECRET}

# Credenciales de EmailJS para el envio de correos de verificacion definidas como variables de entorno
emailjs.service-id=${EMAILJS_SERVICE_ID}
emailjs.template-id=${EMAILJS_TEMPLATE_ID}
emailjs.public-key=${EMAILJS_PUBLIC_KEY}
emailjs.private-key=${EMAILJS_PRIVATE_KEY}