# -----------------------------------------------------------
# CONEXIÓN A LA BASE DE DATOS EN LA NUBE (RAILWAY)
# -----------------------------------------------------------
# URL con parametros de seguridad. OJO: Cambia los datos entre corchetes por los tuyos
spring.datasource.url=jdbc:mysql://maglev.proxy.rlwy.net:10845/railway?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&allowLoadLocalInfile=true

spring.datasource.username=root
spring.datasource.password=FcCfDurFOfCHrOMpZHCVpiiPjLpAVxnc

# -----------------------------------------------------------
# CONFIGURACIÓN DE HIBERNATE / JPA
# -----------------------------------------------------------
# Forzamos el driver y el dialecto para que no haya dudas
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Utilidades de log y actualización de tablas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true